// <auto-generated />
namespace GozdeOzerBitirmeProjesi_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class gozer3001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gozer3001));
        
        string IMigrationMetadata.Id
        {
            get { return "202401302019593_gozer3001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
